network:
  name: my-network
  type: mininet
  topology: tree
  depth: 2
  fanout: 3

monitoring:
  enabled: true
  interval: 5  # in seconds

nodes:
  - name: node1
    type: switch
  - name: node2
    type: host
    ip: 10.0.0.1
  - name: node3
    type: host
    ip: 10.0.0.2

performance:
  metrics:
    - latency
    - throughput
  log_file: /var/log/nfvperf.log
